import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Multi-audience Docusaurus sidebar configuration for the Mehmiro documentation hub.
 * Supports distinct navigation experiences for End Users, Developers, and Researchers.
 */
const sidebars: SidebarsConfig = {
  // Documentación para Usuarios Finales
  userSidebar: [
    {
      type: 'category',
      label: 'Comenzando',
      collapsed: false,
      items: [
        'user/user-intro',
        'user/getting-started/teacher-setup',
        'user/getting-started/student-access'
      ]
    },
    {
      type: 'category',
      label: 'Tutoriales',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'user/tutorials' }
      ]
    },
    {
      type: 'category',
      label: 'Guías de Características',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'user/guides' }
      ]
    }
  ],

  // Documentación del Centro de Desarrollo
  devSidebar: [
    {
      type: 'category',
      label: 'Introducción',
      collapsed: false,
      items: [
        'developer/developer-intro',
        'developer/contributing-to-mehmiro'
      ]
    },
    {
      type: 'category',
      label: 'Arquitectura',
      collapsed: false,
      items: [
        'developer/architecture/system-architecture',
        'developer/architecture/data-model',
        'developer/architecture/multi-app-monorepo',
        'developer/architecture/performance-security'
      ]
    },
    {
      type: 'category',
      label: 'Estándares',
      collapsed: false,
      items: [
        'developer/standards/coding-standards',
        'developer/standards/ui-guidelines',
        'developer/standards/testing-strategy'
      ]
    },
    {
      type: 'category',
      label: 'Procesos de Desarrollo',
      collapsed: false,
      items: [
        'developer/processes/feature-lifecycle',
        'developer/processes/documentation-governance'
      ]
    },
    {
      type: 'category',
      label: 'Documentación de Características',
      collapsed: false,
      items: [
        'developer/features/feature-catalog',
        {
          type: 'category',
          label: 'Perspectivas de Evaluación Estudiantil',
          items: [
            'developer/features/student-assessment-insights/student-assessment-insights-overview',
            'developer/features/student-assessment-insights/student-assessment-insights-architecture',
            'developer/features/student-assessment-insights/student-assessment-insights-bdd'
          ]
        },
        {
          type: 'category',
          label: 'Sistema de Monitoreo Estudiantil',
          items: [
            'developer/features/student-monitoring-system/student-monitoring-system-overview',
            'developer/features/student-monitoring-system/student-monitoring-system-architecture',
            'developer/features/student-monitoring-system/student-monitoring-system-database',
            'developer/features/student-monitoring-system/student-monitoring-system-implementation'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Documentos Fundamentales',
      collapsed: true,
      items: [
        'foundations/persona',
        'foundations/project-overview',
        'foundations/glossary',
        'foundations/core-guidelines'
      ]
    }
  ],

  // Documentación de Investigación
  researchSidebar: [
    {
      type: 'category',
      label: 'Introducción',
      collapsed: false,
      items: [
        'research/research-intro'
      ]
    },
    {
      type: 'category',
      label: 'Metodología de Investigación',
      collapsed: false,
      items: [
        'research/methodology/formative-feedback-methodology'
      ]
    },
    {
      type: 'category',
      label: 'Papers de Investigación',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'research/papers' }
      ]
    }
  ]
};

export default sidebars;
