import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Multi-audience Docusaurus sidebar configuration for the Mehmiro documentation hub.
 * Supports distinct navigation experiences for End Users, Researchers, and Developers.
 * 
 * Priority Order: User Guide > Research > Developers
 */
const sidebars: SidebarsConfig = {
  // ============================================
  // 1. GUÍA DE USUARIO (Primary Audience)
  // ============================================
  guiaSidebar: [
    {
      type: 'category',
      label: 'Comenzando',
      collapsed: false,
      items: [
        'guia/user-intro',
        'guia/getting-started/quick-start',
        'guia/getting-started/teacher-setup',
        'guia/getting-started/student-access'
      ]
    },
    {
      type: 'category',
      label: 'Tutoriales',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'guia/tutorials' }
      ]
    },
    {
      type: 'category',
      label: 'Guías de Características',
      collapsed: false,
      items: [
        'guia/guides/frequently-asked-questions'
      ]
    }
  ],

  // ============================================
  // 2. INVESTIGACIÓN (Secondary Audience)
  // ============================================
  investigacionSidebar: [
    {
      type: 'category',
      label: 'Introducción',
      collapsed: false,
      items: [
        'investigacion/research-intro'
      ]
    },
    {
      type: 'category',
      label: 'Metodología de Investigación',
      collapsed: false,
      items: [
        'investigacion/methodology/formative-feedback-methodology'
      ]
    },
    {
      type: 'category',
      label: 'Papers de Investigación',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'investigacion/papers' }
      ]
    }
  ],

  // ============================================
  // 3. CENTRO DE DESARROLLO (Tertiary Audience)
  // ============================================
  desarrolladoresSidebar: [
    {
      type: 'category',
      label: 'Introducción',
      collapsed: false,
      items: [
        'desarrolladores/developer-intro',
        'desarrolladores/contributing-to-mehmiro'
      ]
    },
    {
      type: 'category',
      label: 'Fundamentos',
      collapsed: true,
      items: [
        'desarrolladores/fundamentos/project-overview',
        'desarrolladores/fundamentos/persona',
        'desarrolladores/fundamentos/glossary',
        'desarrolladores/fundamentos/core-guidelines'
      ]
    },
    {
      type: 'category',
      label: 'Arquitectura',
      collapsed: false,
      items: [
        'desarrolladores/architecture/system-architecture',
        'desarrolladores/architecture/data-model',
        'desarrolladores/architecture/multi-app-monorepo',
        'desarrolladores/architecture/performance-security'
      ]
    },
    {
      type: 'category',
      label: 'Estándares',
      collapsed: false,
      items: [
        'desarrolladores/standards/coding-standards',
        'desarrolladores/standards/ui-guidelines',
        'desarrolladores/standards/testing-strategy'
      ]
    },
    {
      type: 'category',
      label: 'Procesos de Desarrollo',
      collapsed: false,
      items: [
        'desarrolladores/processes/feature-lifecycle',
        'desarrolladores/processes/documentation-governance'
      ]
    },
    {
      type: 'category',
      label: 'Documentación de Características',
      collapsed: false,
      items: [
        'desarrolladores/features/feature-catalog',
        {
          type: 'category',
          label: 'Perspectivas de Evaluación Estudiantil',
          items: [
            'desarrolladores/features/student-assessment-insights/student-assessment-insights-overview',
            'desarrolladores/features/student-assessment-insights/student-assessment-insights-architecture',
            'desarrolladores/features/student-assessment-insights/student-assessment-insights-bdd'
          ]
        },
        {
          type: 'category',
          label: 'Sistema de Monitoreo Estudiantil',
          items: [
            'desarrolladores/features/student-monitoring-system/student-monitoring-system-overview',
            'desarrolladores/features/student-monitoring-system/student-monitoring-system-architecture',
            'desarrolladores/features/student-monitoring-system/student-monitoring-system-database',
            'desarrolladores/features/student-monitoring-system/student-monitoring-system-implementation'
          ]
        }
      ]
    }
  ]
};

export default sidebars;
