import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Multi-audience Docusaurus sidebar configuration for the Mehmiro documentation hub.
 * Supports distinct navigation experiences for End Users, Developers, and Researchers.
 */
const sidebars: SidebarsConfig = {
  // End User Documentation
  userSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'user/intro',
        'user/getting-started/teacher-setup',
        'user/getting-started/student-access'
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'user/tutorials' }
      ]
    },
    {
      type: 'category',
      label: 'Feature Guides',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'user/guides' }
      ]
    }
  ],

  // Developer Hub Documentation
  devSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'developer/intro'
      ]
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'developer/architecture/system-architecture',
        'developer/architecture/data-model',
        'developer/architecture/multi-app-monorepo',
        'developer/architecture/performance-security'
      ]
    },
    {
      type: 'category',
      label: 'Standards',
      collapsed: false,
      items: [
        'developer/standards/coding-standards',
        'developer/standards/ui-guidelines',
        'developer/standards/testing-strategy'
      ]
    },
    {
      type: 'category',
      label: 'Development Processes',
      collapsed: false,
      items: [
        'developer/processes/feature-lifecycle',
        'developer/processes/documentation-governance'
      ]
    },
    {
      type: 'category',
      label: 'Feature Documentation',
      collapsed: false,
      items: [
        'developer/features/feature-catalog',
        {
          type: 'category',
          label: 'Student Assessment Insights',
          items: [
            'developer/features/student-assessment-insights/student-assessment-insights-overview',
            'developer/features/student-assessment-insights/student-assessment-insights-architecture',
            'developer/features/student-assessment-insights/student-assessment-insights-bdd'
          ]
        },
        {
          type: 'category',
          label: 'Student Monitoring System',
          items: [
            'developer/features/student-monitoring-system/student-monitoring-system-overview',
            'developer/features/student-monitoring-system/student-monitoring-system-architecture',
            'developer/features/student-monitoring-system/student-monitoring-system-database',
            'developer/features/student-monitoring-system/student-monitoring-system-implementation'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Foundation Documents',
      collapsed: true,
      items: [
        'foundations/persona',
        'foundations/project-overview',
        'foundations/glossary',
        'foundations/core-guidelines'
      ]
    }
  ],

  // Research Documentation
  researchSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'research/intro'
      ]
    },
    {
      type: 'category',
      label: 'Research Methodology',
      collapsed: false,
      items: [
        'research/methodology/formative-feedback-methodology'
      ]
    },
    {
      type: 'category',
      label: 'Research Papers',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'research/papers' }
      ]
    }
  ]
};

export default sidebars;
